/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accesodelsistema;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class SalaEspera extends javax.swing.JFrame {

    public SalaEspera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedicinas = new javax.swing.JTable();
        btnCargarDatos = new javax.swing.JButton();
        btnRegresarMedicinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableMedicinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Medicina", "Nota", "Hora", "Minuto"
            }
        ));
        jScrollPane1.setViewportView(tableMedicinas);

        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarDatosMouseClicked(evt);
            }
        });
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        btnRegresarMedicinas.setText("Regresar");
        btnRegresarMedicinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMedicinasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarDatos)
                    .addComponent(btnRegresarMedicinas)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnRegresarMedicinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnCargarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarDatosMouseClicked
        readFile("Medicina");
    }//GEN-LAST:event_btnCargarDatosMouseClicked

    private void btnRegresarMedicinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMedicinasMouseClicked
        DatosAlarma alarma = new DatosAlarma();
        this.setVisible(false);
        alarma.setVisible(true);
    }//GEN-LAST:event_btnRegresarMedicinasMouseClicked

    public void readFile(String filename) {

        int arrayLength = 4;

        try {
            File file = new File(filename + ".txt");
            FileReader fRead = new FileReader(file);
            BufferedReader bRead = new BufferedReader(fRead);
            String str;
            int ln = 0;
            int j = 0;
            while ((str = bRead.readLine()) != null) {
                StringTokenizer tokenizer = new StringTokenizer(str, ",");
                String[] content = new String[arrayLength];
                for (int i = 0; tokenizer.hasMoreTokens(); i++) {
                    content[i] = tokenizer.nextToken();
                    tableMedicinas.setValueAt(content[i], j, i);
                }
                j++;
            }

            showModal("Lineas: " + ln);

        } catch (Exception e) {

        }

    }

    public boolean findCredentials(String filename, String username, String password) {
        int found = 0;
        try {
            // Crea el archivo.
            File file = new File(filename + ".txt");
            FileReader fileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            String line;
            String[] users = new String[6];

            // Lee el archivo.
            while ((line = bufferedReader.readLine()) != null) {
                StringTokenizer st = new StringTokenizer(line, ",");

                // Separa por comas al String en pequeños trozos (tokens)
                // y los almacena en un Array.
                for (int i = 0; (st.hasMoreTokens()); i++) {
                    users[i] = st.nextToken();
                }

                // Comprar parametros recibidos con contenido del archivo.
                if (users[1].equals(username) && users[5].equals(password)) {
                    found++;
                }
            }
        } catch (IOException e) {
            showModal("Exception: " + e);
        }
        // Devuelve true o false.
        return found > 1;
    }

    public String showCredentials(String fcUserId) {

        String userid = fcUserId;
        String[] founds = new String[6];

        try {
            File file = new File("file.txt");
            FileReader fileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            String line;
            String[] users = new String[6];

            while ((line = bufferedReader.readLine()) != null) {
                StringTokenizer st = new StringTokenizer(line, ",");

                for (int i = 0; (st.hasMoreTokens()); i++) {
                    users[i] = st.nextToken();
                }

                if (users[0].equals(userid)) {
                    founds = users;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception: " + e);
        }

        return founds[0]
                + "\n"
                + founds[1]
                + "\n"
                + founds[2]
                + "\n"
                + founds[3]
                + "\n"
                + founds[4]
                + "\n"
                + founds[5];
    }

    public void showModal(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaEspera().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnRegresarMedicinas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMedicinas;
    // End of variables declaration//GEN-END:variables
}
